language: python
sudo: false
python:
  - "3.5"
install:
  - pip install -e .
  - pip install -r test_requirements.txt
  - pip install pylint
script: 
  - py.test tests
  - pylint --rcfile=.pylintrc cob
